---
- name: Run all roles on runner hosts
  hosts: runners
  vars_files:
      - "{{ playbook_dir }}/secrets/keys.yml"
      - "{{ playbook_dir }}/secrets/vars.yml"
  roles:
      - role: debian_utils
        remote_user: root
      - conjurer_build
      - gitlab_runner
