---
- name: install qemu-system
  become: yes
  apt:
      pkg:
          - qemu-system
          - libvirt-clients
          - libvirt-daemon-system
      install_recommends: no

- name: add gitlab-runner user to kvm group
  become: yes
  user:
      name: gitlab-runner
      group: kvm
      append: yes

- name: install python 3.x, pip, pkg-config
  become: yes
  apt:
      pkg: 
          - python3
          - python3-dev
          - python3-pip
          - python3-setuptools
          - pkg-config
          - libvirt-dev
          - cloud-image-utils
          - qemu-utils
          - python3-pkg-resources
          - python-setuptools

- name: install poetry
  become: yes
  pip:
      name: poetry
      executable: pip3
